### ISSUE TITLE
Document Upcoming input.multicheckbox field

### ISSUE THREAD

**Issue by RyanMPierson** [gantry/docs#97]
Upcoming Feature in 5.3

This field is a good alternative to the selectize tags when you don’t care about adding new ones and still want to present a choice. It's a simple select option.

![slack-imgs com](https://cloud.githubusercontent.com/assets/4026828/14906591/a16d7f7c-0d82-11e6-8d3b-5158ec013f17.png)

```
include:
      type: input.multicheckbox
      label: Include
      description: What portions of the Outline to inherit
      options:
        attributes: Section Attributes
        particles: Section Children
      default:
        - attributes
        - particles
```
